### ISSUE TITLE
Long scroll menus

### ISSUE THREAD

**Issue by wrybread** [ppizarror/pygame-menu#21]
This seems like a pretty obvious addition: long scrolling menus, for when there's more items than will fit. 

Any idea off the top of your head what would be involved?

**Comment by ppizarror** [comment]
Long scrolling menus:

[USING SCROLLBAR]
1) The problem here is i don't know how to "cut" things: i draw my menu, suppose 600x1000px in total (width, height) but my canvas only supports 600x400, so somehow i need to cut only between (e,400+e)px of the height in order to properly draw things. That's easy with OPENGL clipping window, but with pygame? maybe some opengl should be used.

2) Draw a scrollbar, that's not difficult. Also that scrollbar should handle mouse input: if the user clicks between scrollbar rectangle (and holds) it should move itself and scroll the page.

[USING PAGES]
That's more easy, just create a menu with several pages, if user press any pair of keys (LEFT, RIGHT) the menu must change between page x and x+1, x in (1,n). The number of the page must be drawn somewhere (bottom right corner maybe?)

**Comment by wrybread** [comment]
One possible solution might be to scroll down the items and when at the bottom it loads a new page and scrolling starts again... Ideally with a little animation to show the transition. Might be tricky if scrolling up and down through that border area though.

**Comment by ppizarror** [comment]
I'll work on this in the following weeks

**Comment by sharkwouter** [comment]
I've been trying to get pagination to work with a selector, but onchange doesn't seem to allow you to load a new menu.

**Comment by sharkwouter** [comment]
> > I've been trying to get pagination to work with a selector, but onchange doesn't seem to allow you to load a new menu.
> 
> Do you have any working example?

I am trying to use it for my flatpak-manager for SteamOS. The code I was talking about can be found here: https://github.com/sharkwouter/flatpak-manager/blob/master/flatpak-manager-steamos/flatpakmanager_steamos/gui.py#L97

If you'd like to test that code, you can execute  flatpak-manager/flatpak-manager-steamos/flatpak-manager-steamos  script to test it. It is specific to Linux, though, and requires flatpak to be installed.

**Comment by sharkwouter** [comment]
No problem, I made a simplified version with just the paged menu here: https://gist.github.com/sharkwouter/ec465d36f6f9fd1570e17511c570f36c

Don't pay too much attention to calculation which determines how many pages there are. It can be off by one with different range sizes.

**Comment by ppizarror** [comment]
Thanks, I'll check this issue

**Comment by ppizarror** [comment]
Related issue: #15
