### ISSUE TITLE
Label cannot handle nextline '\n'

### ISSUE THREAD

**Issue by mrkprdo** [ppizarror/pygame-menu#312]
```python
app_name = self.app_screen.add.label("Hello World\nApp")
app_name.set_font(
                font=pygame_menu.font.FONT_MUNRO,
                font_size=22,
                color=(219, 48, 33),
                selected_color=(93,132,100),
                readonly_color=(93,132,100),
                readonly_selected_color=(93,132,100),
                background_color=(33, 42, 217)
                )
```

with this code, set_font breaks and it is treating it like a list, here is the exception:
```bash
Traceback (most recent call last):
  File "/main_app.py", line 8, in <module>
    screen.load_ui()
  File "/path/mainscreen.py", line 75, in load_ui
    self.screen_to_update = self.apps.open()
  File "/path/apps_ui.py", line 53, in open
    return hw_app.get_screen()
  File "/path/helloworld.py", line 19, in get_screen
    app_name.set_font(
AttributeError: 'list' object has no attribute 'set_font'
```

There are two ways to handle this:
1 Take all other whitespace chars and treat it like space (except space itself)
2 Add nextline support and automatically set its position

**Comment by ppizarror** [comment]
Since v3 the label() method, if create a multi-line label, it returns a list of objects (labels). The reason behind that is the user can control with full freedom the behavior of the objects.

In response:
1. I don't quite understand your idea. Labels don't implement word-wrapping, them only create a surface object (returned by the font). The idea behind breaking is that, after some size has reached, or \n is present, a new widget is created considering the same x-position, but adding the previous line height to the vertical position. It's a much more easier approach than word-wrapping.
2. That is what is done. Nextline what does is returning a list of widgets (labels), thus, user can write them as follows:

```python
for n in line:
   n.whatever()
```

Now, a new approach could be done which keeps the philosophy of "only return widgets" is that a new widget class can be created, named "MultiLabel" which basically is a class that contains a list of labels. Each method supported by the label is rewritten, such as set_font, translate, etc...

**Comment by ppizarror** [comment]
Also, the documentation shows that the add.line() method returns: "Widget object, or List of widgets if the text overflows"

**Comment by ppizarror** [comment]
On the other hand, creating additional widgets makes the library much more complex, and only solves the issue about iterating through the widgets. Considering that I prefer to clarify the documentation. The problem also about the widgetlist is that each parameter must be rewritten, and not each widget will work with this approach, thus, ImageList, DropselectiorList,... must be done.

**Comment by mrkprdo** [comment]
Ahh, thanks for the tip.
I was trying to understand why it was doing that.
Found this [part of widgetmanager](https://github.com/ppizarror/pygame-menu/blob/223ffd07d2b688b1bb0bade0b73f59c4cc1e8dc9/pygame_menu/_widgetmanager.py#L1025)

My bad, tbh, i'm still fairly new with this library thanks for your response.
I will go through the documentation once again to better understand its usage.

**Comment by ppizarror** [comment]
As you see, the behavior is very simple. Once \n is found, just insert N items within the Menu. The menu then will update the position of each widget. Maybe a new widget can be used instead, for example "MultiLabel" widget can be created. This label has a list of string chars, which pastes into a larger surface object. The difference with the current solution is that it's a Widget that inherits all the properties of the core Widget class, and implements all the features without worrying about lists.

If you have any suggestions, feel free to push any push request you want.
