### ISSUE TITLE
Custom Image as Background

### ISSUE THREAD

**Issue by NaphanB** [ppizarror/pygame-menu#377]
Hi, I am trying to add a custom image for a menu background but I can only find example code for the example image which comes with pygame-menu. So I am unsure of how to use a custom image for the background, as I am quite new to pygame and pygame-menu. Thanks for your help and thank you for providing such useful code to make menus with.

**Comment by ppizarror** [comment]
Hi, for such purpose, you must set ``background_color`` on a given theme with a ``BaseImage`` object of your choice. Here is an example (which I've added to example image):

``python
theme_bg_image = main_menu_theme.copy()
theme_bg_image.background_color = pygame_menu.BaseImage(
    image_path=pygame_menu.baseimage.IMAGE_EXAMPLE_CARBON_FIBER # here is the path of your image
)
theme_bg_image.title_font_size = 25
menu_with_bg_image = pygame_menu.Menu(
    height=WINDOW_SIZE[1] * 0.7,
    onclose=pygame_menu.events.EXIT,
    theme=theme_bg_image,
    title='Menu with background image',
    width=WINDOW_SIZE[0] * 0.8
)
menu_with_bg_image.add.button('Back', pygame_menu.events.BACK)
``

Result:
![image](https://user-images.githubusercontent.com/12925256/148787808-162ee61e-e0b1-451a-9229-760b6c29357c.png)

Hope this solves your issue. I'll update the repo after this issue is closed.

**Comment by ppizarror** [comment]
See updated example: https://github.com/ppizarror/pygame-menu/blob/d9e52de2f5b1f512e305a6da86093afb96c822da/pygame_menu/examples/other/image_background.py#L68-L80

**Comment by ppizarror** [comment]
Hello. Any updates? Have you fixed the error? I'm closing this thread by now. Greetings,

Pablo
