### ISSUE TITLE
Save text input from menu to variable.

### ISSUE THREAD

**Issue by NaphanB** [ppizarror/pygame-menu#378]
In my program I am allowing the player to choose their name from the main menu, and I later that players name and score is written to file, I am unsure how to do this as I cannot seem to save the player's name into a variable.

**Comment by ppizarror** [comment]
Hi, it's actually not possible to store into a variable by the menu itself. Usually, that behavior is extended by the user instead of the UI (software design patterns).

To save the player's name into a variable you can create an "on_return" method to a menu button (for example, save). This method, after fired, can retrieve the menu widget values and store to a file, for example:

```python
import pygame_menu
from pygame_menu.examples import create_example_window

surface = create_example_window('Example - Simple', (600, 400))
menu = pygame_menu.Menu(
    height=300,
    theme=pygame_menu.themes.THEME_BLUE,
    title='Welcome',
    width=400
)

user_name = menu.add.text_input('Name: ', default='John Doe', maxchar=10)
def save_to_file():
    with open('_test_saveparams.cfg', 'w') as f:
        f.write(f'USERNAME={user_name.get_value()}')
menu.add.button('Save', save_to_file)
menu.add.button('Quit', pygame_menu.events.EXIT)
menu.mainloop(surface)
```

This menu, after pressing "save", saves the data to a file. You also don't require the "user_name" variable reference. You can get the menu value using the widget ID:

```python
import pygame_menu
from pygame_menu.examples import create_example_window

surface = create_example_window('Example - Simple', (600, 400))
menu = pygame_menu.Menu(
    height=300,
    theme=pygame_menu.themes.THEME_BLUE,
    title='Welcome',
    width=400
)

def save_to_file():
    with open('_test_saveparams.cfg', 'w') as f:
        f.write(f'USERNAME={menu.get_widget("username").get_value()}')

menu.add.text_input('Name: ', textinput_id='username', default='John Doe', maxchar=10)
menu.add.button('Save', save_to_file)
menu.add.button('Quit', pygame_menu.events.EXIT)
menu.mainloop(surface)
```

Hope this solves your issue

**Comment by ppizarror** [comment]
Hello. Any updates? Have you fixed the error? I'm closing this thread by now. Greetings,

Pablo
