### ISSUE TITLE
The color of the button text does not change

### ISSUE THREAD

**Issue by UltraRobot2017** [ppizarror/pygame-menu#433]
Hi, I think I found a bug or I'm doing something wrong, I change the color of the button text, but it doesn't change in any way, I made an underscore of the same color and everything works, but there are problems with the text color.

[TEST.zip](https://github.com/ppizarror/pygame-menu/files/10279686/TEST.zip)

![image](https://user-images.githubusercontent.com/32699896/208961039-69d54f3d-4050-4d20-9df7-d63aeabf2115.png)

**Comment by UltraRobot2017** [comment]
When I added the second button, the text color was already displayed correctly on the button.
![image](https://user-images.githubusercontent.com/32699896/209153120-26a9c3bc-3a84-45ed-9b0b-994990bee37e.png)



[TEST.zip](https://github.com/ppizarror/pygame-menu/files/10287533/TEST.zip)

**Comment by ppizarror** [comment]
Hi! The problem relies on the selection effect rather than the color of the widget. The default selection effect belongs to ``HighlightSelection``, which uses selection color ``(255, 255, 255)``,  therefore you see a white text instead of the red (first example you sent).

However, if set the selection effect to ``None``:

```python
theme_menu = pygame_menu.themes.THEME_DEFAULT.copy()
theme_menu.widget_selection_effect = None
menu = pygame_menu.Menu(..., theme=theme_menu)
menu.add.button('Quit', font_size=40, underline=True, underline_color=(255, 0, 0), font_color=(255, 0, 0))
```

You get:
![asdf](https://user-images.githubusercontent.com/12925256/209188725-8f1861ca-8731-4cdc-94ff-fa1af0551004.png)

**Comment by UltraRobot2017** [comment]
Thank you!
