### ISSUE TITLE
pygame-ce requirement

### ISSUE THREAD

**Issue by JaskRendix** [ppizarror/pygame-menu#460]
Hello there,

I noticed that in your requirements.txt there is `pygame>=1.9.3`
Have you considered to switch to [pygame-ce](https://github.com/pygame-community/pygame-ce)?

_It is a fork of the upstream pygame project by its former core developers, and was created after impossible challenges prevented them from continuing development upstream. The new distribution aims to offer more frequent releases, continuous bugfixes and enhancements, and a more democratic governance model._

A couple of days ago they release a new [version 2.2.0](https://github.com/pygame-community/pygame-ce/releases/tag/2.2.0) and it fixes a lot of issues.

The community is very active.

**Comment by ppizarror** [comment]
It is there any compatibility issues if I migrate to ``pygame-ce``? Can I add both ``pygame`` and ``pygame-ce`` to requirements.txt?, or just I need to replace it?

**Comment by JaskRendix** [comment]
No compatibility issues for me. I replaced it (as it has been advised in the 2.2.0 release), but if you have specific doubts/questions, then you can ask directly on `pygame-ce`, they are for sure more skilled than me on the topic as well as really reactive.

**Comment by leestarb** [comment]
Hello! I would not be happy if pygame-menu will move its base to pygame-ce. I think you can just make a fork of pygame-menu, but optimise it for pygame-ce.

**Comment by ppizarror** [comment]
I also agree with @leestarb. Thus, I've created a new branch that will be updated after each version. See https://github.com/ppizarror/pygame-menu/tree/pygame-ce. All pygame-menu tests have successfully passed.. so I'll create a new version v4.4.1, today, publishing both ``pygame-menu`` and ``pygame-menu-ce`` to pip. @JaskRendix.

**Comment by JaskRendix** [comment]
Thank you so much! @ppizarror

**Comment by ppizarror** [comment]
Hi, check out brand new https://pypi.org/project/pygame-menu-ce/

**Comment by neilsimp1** [comment]
Hi @ppizarror 
Sorry to bug you, but by any chance are you looking considering updating pygame-menu-ce with the more recent changes from pygame-menu?

I'm happy to look this weekend and if it's a simple rebase I will submit a PR.

**Comment by ppizarror** [comment]
Hi @neilsimp1 , It is there any chance to have an attribute in Menu to make it "ce-compatible"? I guess that having a single repo is the best approach. I am thinking about

```python
menu = Menu(...., ce_mode=True)
```

**Comment by ppizarror** [comment]
I'd love if you can come up with an idea, feel free to create a PR for this

**Comment by neilsimp1** [comment]
Hello @ppizarror ,


To start off with, the stuff I mentioned above about using pygame-ce's `pygame.Window` object, I gave up on.
When trying to use `Window` without using pygame-menu, I would still get errors about not having called `pygame.display.set_mode()` from my own code.

The problem is likely my own lack of understanding, but I've decided I don't care anymore since the code works with the way that I have it :).

___


However, there is still an issue. While I was right to say that pygame-menu still runs fine when using pygame-ce, the fact that I have pygame-menu still installed, and that it has pygame as a dependency, means that my venv still gets pygame installed.
This worked when I manually uninstalled pygame and installed pygame-ce.
But, if I delete the venv and start over, then `pipenv install` seems to get confused and install pygame over the top of pygame-ce, and then the program runs using regular pygame instead of pygame-ce.
I only noticed when I started getting errors for pygame-ce specific functions not existing.

I can work around this problem by installing dependencies, removing pygame, and then installing pygame-ce.


Which brings me to this: https://github.com/neilsimp1/pygame-menu/tree/pygame-menu-ce
I saw what you did [here](https://github.com/ppizarror/pygame-menu/commit/f869f3694006767edfbbc3027eea1f75a41a9e11) and basically just applied the same/similar changes against the latest code from master. 
Testing locally in my project, this did work to install and use pygame-menu and pygame-ce without installing pygame.

One odd thing is that `test_invalid_images()` was failing due to the size of the python.svg file. I [shrunk the svg size](https://github.com/neilsimp1/pygame-menu/actions/runs/13476729218) to get CI tests passing.


I was not sure if you would want this in a PR or not or if you even want to try and keep https://pypi.org/project/pygame-menu-ce/ up to date with https://pypi.org/project/pygame-menu/.
I agree with your statement that a single repo is the best approach, and even having a single package to pip install is better than two.

That's a problem I'm not sure how to solve, though. Maybe it is possible, but I don't know how a package could be built in a way where it could depend on one package OR another (pygame or pygame-ce, in this case).

So, I'm mostly hoping to hear your thoughts. If you want to move the talk out of this Issue I am happy to email or anything else.

Cheers :)

**Comment by ppizarror** [comment]
Hi @neilsimp1 Today i re-opened the ce-branch and updated it with all new features. Greetings

**Comment by neilsimp1** [comment]
Thank you so much, you wonderful person!

Sorry this took so long to reply  I will give this a try soon.
I'm nearing completion of my project and it uses Pygame Menu extensively. I'd be happy to share it with you when it's ready.
