### ISSUE TITLE
Can not use BACK key

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#72]
Hello @ppizarror , I made some tests on the last version 2.0.3, it seems that the BACK don't go to previous menu anymore. This is the same behavior with examples.

Maybe something new to configure in the menu?

**Comment by ppizarror** [comment]
Hi! I had to implement many changes in 2.0.3 to add multiple menu compatibility #71 
Anyway, I found how to fix this:

Change self._actual.prev to self._top._prev in:
https://github.com/ppizarror/pygame-menu/blob/37d4ae6a6b1b6c1029c475caf0192d14be849494/pygameMenu/menu.py#L827

With this solution the bug is fixed.
If you find any other error please create a new issue as always.
Greetings from 🆑

**Comment by ppizarror** [comment]
Commited the changes to the repo:
https://github.com/ppizarror/pygame-menu/commit/25bee64767147f43a5f44c54791263fca5520934

**Comment by anxuae** [comment]
Thanks, this solves the issue

**Comment by ppizarror** [comment]
Version 2.0.4 uploaded
